LPS-177843
alinedoleron/liferay-portal pull request #220
Opened 2023-03-07 21:38 UTC by alinedoleron

2023-03-07 21:38 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-03-07 21:38 UTC, alinedoleron commented
ci:test:sf

2023-03-07 21:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4092/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4092/jenkins-report.html">here</a>.</b></p>

2023-03-07 21:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bddc1a8e1fcdae32d381ec8fd788f809ce5026aa">bddc1a8e1fcdae32d381ec8fd788f809ce5026aa</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-177843">LPS-177843</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/f2050f3c390912e228a7cf92afcd224296bf2a06">f2050f3c390912e228a7cf92afcd224296bf2a06</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4092/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4092/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/components/DashboardTable/DashboardEmptyTable.scss expected:&lt;... Pro', sans-serif;
     [java]   [padding: 64px 468px;
     [java]   text-align: center];
     [java] 
     [java]   &amp;-description \{
     [java] ...&gt; but was:&lt;... Pro', sans-serif;
     [java]   [text-align: center;
     [java]   padding: 64px 468px];
     [java] 
     [java]   &amp;-description \{
     [java] ...&gt;
     [java] 2: ./workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/assets/images/no-app.svg expected:&lt;&lt;svg [fill="none" height="80" viewBox="0 0 144 80" width="144" xmlns="http://www.w3.org/2000/svg"&gt;
     [java]   &lt;rect fill="#E7EFFF" height="80" rx="8" width="144" /&gt;
     [java]   &lt;mask height="32" id="mask0_556_34559" maskUnits="userSpaceOnUse" style="mask-type:alpha" width="32" x="56" y="24"&gt;
     [java]     &lt;path d="M86.9379 24.001H80.95C80.4003 24.001 79.9531 24.4481 79.9531 25.0001V30.988C79.9531 31.54 80.4003 31.9871 80.9522 31.9871H86.9401C87.4921 31.9871 87.9392 31.5399 87.9392 30.988V25.0001C87.9369 24.448 87.4899 24.001 86.9379 24.001Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M62.9889 35.9768H57.0011C56.449 35.9768 56.002 36.4239 56.002 36.9759V42.9638C56.002 43.5158 56.4491 43.9629 57.0011 43.9629H62.9889C63.541 43.9629 63.9858 43.5158 63.9858 42.9638V36.9759C63.9858 36.4239 63.5387 35.9768 62.9889 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M74.9616 35.9768H68.9737C68.4217 35.9768 67.9746 36.4239 67.9746 36.9759V42.9638C67.9746 43.5158 68.4217 43.9629 68.9737 43.9629H74.9616C75.5136 43.9629 75.9607 43.5158 75.9607 42.9638V36.9759C75.9607 36.4239 75.5136 35.9768 74.9616 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M86.9382 35.9768H80.9503C80.3983 35.9768 79.9512 36.4239 79.9512 36.9759V42.9638C79.9512 43.5158 80.3983 43.9629 80.9503 43.9629H86.9382C87.4901 43.9629 87.9373 43.5158 87.9373 42.9638V36.9759C87.9373 36.4239 87.4901 35.9768 86.9382 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M62.9889 47.9524H57.0011C56.449 47.9524 56.002 48.3995 56.002 48.9515V54.9394C56.002 55.4891 56.4491 55.9362 57.0011 55.9362H62.9889C63.541 55.9362 63.9858 55.4891 63.9858 54.9371V48.9493C63.9858 48.3995 63.5387 47.9524 62.9889 47.9524Z" fill="#6B6C7E" /&gt;</pre></details></html>

2023-03-07 21:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4092/">test-portal-source-format#4092</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4092/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alinedoleron/liferay-portal/pull/220">alinedoleron#220</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2223760423">[master] ci:test:sf - alinedoleron &gt; alinedoleron - PR#220 - 2023-03-07[13:39:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/15351/">publish-testray-report#15351</a><br/></div></div>

2023-03-08 13:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/4776/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4776/jenkins-report.html">here</a>.</b></p>

2023-03-08 13:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3">7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-177843">LPS-177843</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/b03891e8ff468e230583e29e3212d923e25e154d">b03891e8ff468e230583e29e3212d923e25e154d</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4776/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4776/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/components/DashboardTable/DashboardEmptyTable.scss expected:&lt;... Pro', sans-serif;
     [java]   [padding: 64px 468px;
     [java]   text-align: center];
     [java] 
     [java]   &amp;-description \{
     [java] ...&gt; but was:&lt;... Pro', sans-serif;
     [java]   [text-align: center;
     [java]   padding: 64px 468px];
     [java] 
     [java]   &amp;-description \{
     [java] ...&gt;
     [java] 2: ./workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/assets/images/no-app.svg expected:&lt;&lt;svg [fill="none" height="80" viewBox="0 0 144 80" width="144" xmlns="http://www.w3.org/2000/svg"&gt;
     [java]   &lt;rect fill="#E7EFFF" height="80" rx="8" width="144" /&gt;
     [java]   &lt;mask height="32" id="mask0_556_34559" maskUnits="userSpaceOnUse" style="mask-type:alpha" width="32" x="56" y="24"&gt;
     [java]     &lt;path d="M86.9379 24.001H80.95C80.4003 24.001 79.9531 24.4481 79.9531 25.0001V30.988C79.9531 31.54 80.4003 31.9871 80.9522 31.9871H86.9401C87.4921 31.9871 87.9392 31.5399 87.9392 30.988V25.0001C87.9369 24.448 87.4899 24.001 86.9379 24.001Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M62.9889 35.9768H57.0011C56.449 35.9768 56.002 36.4239 56.002 36.9759V42.9638C56.002 43.5158 56.4491 43.9629 57.0011 43.9629H62.9889C63.541 43.9629 63.9858 43.5158 63.9858 42.9638V36.9759C63.9858 36.4239 63.5387 35.9768 62.9889 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M74.9616 35.9768H68.9737C68.4217 35.9768 67.9746 36.4239 67.9746 36.9759V42.9638C67.9746 43.5158 68.4217 43.9629 68.9737 43.9629H74.9616C75.5136 43.9629 75.9607 43.5158 75.9607 42.9638V36.9759C75.9607 36.4239 75.5136 35.9768 74.9616 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M86.9382 35.9768H80.9503C80.3983 35.9768 79.9512 36.4239 79.9512 36.9759V42.9638C79.9512 43.5158 80.3983 43.9629 80.9503 43.9629H86.9382C87.4901 43.9629 87.9373 43.5158 87.9373 42.9638V36.9759C87.9373 36.4239 87.4901 35.9768 86.9382 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M62.9889 47.9524H57.0011C56.449 47.9524 56.002 48.3995 56.002 48.9515V54.9394C56.002 55.4891 56.4491 55.9362 57.0011 55.9362H62.9889C63.541 55.9362 63.9858 55.4891 63.9858 54.9371V48.9493C63.9858 48.3995 63.5387 47.9524 62.9889 47.9524Z" fill="#6B6C7E" /&gt;</pre></details></html>

2023-03-08 13:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4776/">test-portal-source-format#4776</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4776/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alinedoleron/liferay-portal/pull/220">alinedoleron#220</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2224805374">[master] ci:test:sf - alinedoleron &gt; alinedoleron - PR#220 - 2023-03-08[05:15:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/3251/">publish-testray-report#3251</a><br/></div></div>

2023-03-08 13:29 UTC, alinedoleron commented
ci:test:sf

2023-03-08 14:20 UTC, alinedoleron commented
ci:stop

2023-03-08 14:21 UTC, alinedoleron commented
ci:test:sf

2023-03-08 14:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/268/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/268/jenkins-report.html">here</a>.</b></p>

2023-03-08 14:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3">7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-177843">LPS-177843</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/33120e828599fdb5bf38d2c2a6a379340a999df9">33120e828599fdb5bf38d2c2a6a379340a999df9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/268/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/268/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/assets/images/no-app.svg expected:&lt;&lt;svg [fill="none" height="80" viewBox="0 0 144 80" width="144" xmlns="http://www.w3.org/2000/svg"&gt;
     [java]   &lt;rect fill="#E7EFFF" height="80" rx="8" width="144" /&gt;
     [java]   &lt;mask height="32" id="mask0_556_34559" maskUnits="userSpaceOnUse" style="mask-type:alpha" width="32" x="56" y="24"&gt;
     [java]     &lt;path d="M86.9379 24.001H80.95C80.4003 24.001 79.9531 24.4481 79.9531 25.0001V30.988C79.9531 31.54 80.4003 31.9871 80.9522 31.9871H86.9401C87.4921 31.9871 87.9392 31.5399 87.9392 30.988V25.0001C87.9369 24.448 87.4899 24.001 86.9379 24.001Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M62.9889 35.9768H57.0011C56.449 35.9768 56.002 36.4239 56.002 36.9759V42.9638C56.002 43.5158 56.4491 43.9629 57.0011 43.9629H62.9889C63.541 43.9629 63.9858 43.5158 63.9858 42.9638V36.9759C63.9858 36.4239 63.5387 35.9768 62.9889 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M74.9616 35.9768H68.9737C68.4217 35.9768 67.9746 36.4239 67.9746 36.9759V42.9638C67.9746 43.5158 68.4217 43.9629 68.9737 43.9629H74.9616C75.5136 43.9629 75.9607 43.5158 75.9607 42.9638V36.9759C75.9607 36.4239 75.5136 35.9768 74.9616 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M86.9382 35.9768H80.9503C80.3983 35.9768 79.9512 36.4239 79.9512 36.9759V42.9638C79.9512 43.5158 80.3983 43.9629 80.9503 43.9629H86.9382C87.4901 43.9629 87.9373 43.5158 87.9373 42.9638V36.9759C87.9373 36.4239 87.4901 35.9768 86.9382 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M62.9889 47.9524H57.0011C56.449 47.9524 56.002 48.3995 56.002 48.9515V54.9394C56.002 55.4891 56.4491 55.9362 57.0011 55.9362H62.9889C63.541 55.9362 63.9858 55.4891 63.9858 54.9371V48.9493C63.9858 48.3995 63.5387 47.9524 62.9889 47.9524Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M74.9616 47.9524H68.9737C68.4217 47.9524 67.9746 48.3995 67.9746 48.9515V54.9394C67.9746 55.4914 68.4217 55.9385 68.9737 55.9385H74.9616C75.5136 55.9385 75.9607 55.4914 75.9607 54.9394V48.9515C75.9607 48.3995 75.5136 47.9524 74.9616 47.9524Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M86.9382 47.9525H80.9503C80.3983 47.9525 79.9512 48.3996 79.9512 48.9516V54.9394C79.9512 55.4914 80.3983 55.9385 80.9503 55.9385H86.9382C87.4901 55.9362 87.9373 55.4892 87.9373 54.9371V48.9493C87.9373 48.3995 87.4901 47.9525 86.9382 47.9525Z" fill="#6B6C7E" /&gt;</pre></details></html>

2023-03-08 14:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/268/">test-portal-source-format#268</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/268/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alinedoleron/liferay-portal/pull/220">alinedoleron#220</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2224890389">[master] ci:test:sf - alinedoleron &gt; alinedoleron - PR#220 - 2023-03-08[06:21:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/602/">publish-testray-report#602</a><br/></div></div>

2023-03-08 15:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/5861/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5861/jenkins-report.html">here</a>.</b></p>

2023-03-08 15:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3">7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-177843">LPS-177843</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/33120e828599fdb5bf38d2c2a6a379340a999df9">33120e828599fdb5bf38d2c2a6a379340a999df9</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5861/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5861/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/assets/images/no-app.svg expected:&lt;&lt;svg [fill="none" height="80" viewBox="0 0 144 80" width="144" xmlns="http://www.w3.org/2000/svg"&gt;
     [java]   &lt;rect fill="#E7EFFF" height="80" rx="8" width="144" /&gt;
     [java]   &lt;mask height="32" id="mask0_556_34559" maskUnits="userSpaceOnUse" style="mask-type:alpha" width="32" x="56" y="24"&gt;
     [java]     &lt;path d="M86.9379 24.001H80.95C80.4003 24.001 79.9531 24.4481 79.9531 25.0001V30.988C79.9531 31.54 80.4003 31.9871 80.9522 31.9871H86.9401C87.4921 31.9871 87.9392 31.5399 87.9392 30.988V25.0001C87.9369 24.448 87.4899 24.001 86.9379 24.001Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M62.9889 35.9768H57.0011C56.449 35.9768 56.002 36.4239 56.002 36.9759V42.9638C56.002 43.5158 56.4491 43.9629 57.0011 43.9629H62.9889C63.541 43.9629 63.9858 43.5158 63.9858 42.9638V36.9759C63.9858 36.4239 63.5387 35.9768 62.9889 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M74.9616 35.9768H68.9737C68.4217 35.9768 67.9746 36.4239 67.9746 36.9759V42.9638C67.9746 43.5158 68.4217 43.9629 68.9737 43.9629H74.9616C75.5136 43.9629 75.9607 43.5158 75.9607 42.9638V36.9759C75.9607 36.4239 75.5136 35.9768 74.9616 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M86.9382 35.9768H80.9503C80.3983 35.9768 79.9512 36.4239 79.9512 36.9759V42.9638C79.9512 43.5158 80.3983 43.9629 80.9503 43.9629H86.9382C87.4901 43.9629 87.9373 43.5158 87.9373 42.9638V36.9759C87.9373 36.4239 87.4901 35.9768 86.9382 35.9768Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M62.9889 47.9524H57.0011C56.449 47.9524 56.002 48.3995 56.002 48.9515V54.9394C56.002 55.4891 56.4491 55.9362 57.0011 55.9362H62.9889C63.541 55.9362 63.9858 55.4891 63.9858 54.9371V48.9493C63.9858 48.3995 63.5387 47.9524 62.9889 47.9524Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M74.9616 47.9524H68.9737C68.4217 47.9524 67.9746 48.3995 67.9746 48.9515V54.9394C67.9746 55.4914 68.4217 55.9385 68.9737 55.9385H74.9616C75.5136 55.9385 75.9607 55.4914 75.9607 54.9394V48.9515C75.9607 48.3995 75.5136 47.9524 74.9616 47.9524Z" fill="#6B6C7E" /&gt;
     [java]     &lt;path d="M86.9382 47.9525H80.9503C80.3983 47.9525 79.9512 48.3996 79.9512 48.9516V54.9394C79.9512 55.4914 80.3983 55.9385 80.9503 55.9385H86.9382C87.4901 55.9362 87.9373 55.4892 87.9373 54.9371V48.9493C87.9373 48.3995 87.4901 47.9525 86.9382 47.9525Z" fill="#6B6C7E" /&gt;</pre></details></html>

2023-03-08 16:01 UTC, alinedoleron commented
ci:test:sf

2023-03-08 16:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/4134/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4134/jenkins-report.html">here</a>.</b></p>

2023-03-08 16:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3">7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-177843">LPS-177843</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/00051c36c4304a26b4e0bcb5722fa79944961a8d">00051c36c4304a26b4e0bcb5722fa79944961a8d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4134/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4134/jenkins-report.html">here</a>.</h5></details></html>

2023-03-08 16:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4134/">test-portal-source-format#4134</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4134/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alinedoleron/liferay-portal/pull/220">alinedoleron#220</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2224958498">[master] ci:test:sf - alinedoleron &gt; alinedoleron - PR#220 - 2023-03-08[08:01:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/14711/">publish-testray-report#14711</a><br/></div></div>

2023-03-08 16:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/5861/">test-portal-source-format#5861</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/5861/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alinedoleron/liferay-portal/pull/220">alinedoleron#220</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2224962547">[master] ci:test:sf - alinedoleron &gt; alinedoleron - PR#220 - 2023-03-08[07:15:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/3313/">publish-testray-report#3313</a><br/></div></div>

2023-03-08 17:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/3474/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3474/jenkins-report.html">here</a>.</b></p>

2023-03-08 17:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/3474/">test-portal-acceptance-pullrequest(master)#3474</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3474/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alinedoleron/liferay-portal/pull/220">alinedoleron#220</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2224968284">[master] ci:test:relevant - alinedoleron &gt; alinedoleron - PR#220 - 2023-03-08[09:20:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/7823/">publish-testray-report#7823</a><br/></div></div>

2023-03-09 12:48 UTC, naraandrade commented
@alinedoleron We need also to create a page to display the My Apps Dashboard in addition to creating the empty state for the table. Could you please implement it? Thanks :)

2023-03-09 16:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4105/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4105/jenkins-report.html">here</a>.</b></p>

2023-03-09 16:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4105/">test-portal-source-format#4105</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4105/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alinedoleron/liferay-portal/pull/220">alinedoleron#220</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2226351038">[master] ci:test:sf - alinedoleron &gt; alinedoleron - PR#220 - 2023-03-09[08:49:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/15401/">publish-testray-report#15401</a><br/></div></div>

2023-03-09 19:22 UTC, naraandrade requested changes

2023-03-09 19:22 UTC, naraandrade commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/components/DashboardTable/DashboardTable.tsx
> +	description2: string,
@alinedoleron there's a format issue here, could you fix it please? Thanks :)

2023-03-09 19:22 UTC, naraandrade commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/components/DashboardTable/DashboardTable.tsx
> +	if (!apps.length) {
@alinedoleron Please, add a blank line between the declaration of `description1, description2, title` and their usage.

2023-03-09 19:22 UTC, naraandrade commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/DashBoardPage/DashboardPage.tsx
> +		title: string},
@alinedoleron format issue here too.

2023-03-09 20:13 UTC, alinedoleron commented
ci:test:sf

2023-03-09 20:16 UTC, alinedoleron commented
Hi @naraandrade. I've made the requested changes. Thanks!

2023-03-09 20:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/294/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/294/jenkins-report.html">here</a>.</b></p>

2023-03-09 20:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3">7167fb45ee3ac3dc7e131e36c7a8d06997a43cf3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/alinedoleron/liferay-portal/tree/LPS-177843">LPS-177843</a><br/>Branch GIT ID: <a href="https://github.com/alinedoleron/liferay-portal/commit/ec7d77b479e2ca9f16b17c4c2edf42fbf5fa4019">ec7d77b479e2ca9f16b17c4c2edf42fbf5fa4019</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/294/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/294/jenkins-report.html">here</a>.</h5></details></html>

2023-03-09 20:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/294/">test-portal-source-format#294</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/294/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/alinedoleron/liferay-portal/pull/220">alinedoleron#220</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2226541406">[master] ci:test:sf - alinedoleron &gt; alinedoleron - PR#220 - 2023-03-09[12:14:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/693/">publish-testray-report#693</a><br/></div></div>

2023-03-09 22:25 UTC, naraandrade commented
Just started reviewing :)

2023-03-09 22:35 UTC, naraandrade commented
Resent here: https://github.com/naraandrade/liferay-portal/pull/167.

2023-03-09 22:35 UTC, closed without merging